# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0b2dec49daab2b34070212962c6b690f4d7c9455f7e674ce10d2b63b9b2e516281154acc276ffddaf0f2849a7aea63d856351f10e4c4913ba0f48e50de3ffb1

test:
  secret_key_base: ee0c242625b347262cbe8e543f9951914fe4bab349b39e3c32c79ee443be695f50ebc1a2bbb98b522947c3d0f183df81480758e9adbfd4a7c6c78bbbba5cbf36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
